apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: glennc@microsoft.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}